#!/usr/bin/env bash
#stops 4-to_infinity_and_beyond process.
pid=$(pgrep -f 4-to_infinity_and_beyond)
kill="$pid"

while kill -O "$pid" 2> /dev/null; do
	seep 1
done

if kill -O "$pid" 2> /dev/null; then
	kill -9 "$pid"
fi
