#!/usr/bin/env bash
#stops 4-to_infinity_and_beyond process
pid=$(ps -ef | grep "4-to_infinity_and_beyond" | grep -v grep | awk '{print $2}')

if [ -n "$pid" ]; then
	pkill -TERM -P $pid
	echo "Stopped the 4-to_infinity_and_beyond process with PID $pid"
else
	echo "Could not find the 4-to_infinity_and_beyond process"
fi
