#!/usr/bin/env bash
#displays:
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

function handle_sigterm {
  echo "I am invincible!!!"
  exit 0
}

trap handle_sigterm SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done

pid=$(pgrep -f "7-highlander")

function handle_sigterm {
  kill "$pid"
  echo "There can be only one!"
  exit 0
}

trap handle_sigterm SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
