#!/usr/bin/env bash
#displays the content of the file /etc/passwd.
# shellcheck disable=SC2034
while IFS=: read -r username x uid gid description home shell; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home directory: $home"
done < "/etc/passwd"
