#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
hour=0
minute=1
while [ $hour -le 12 ] || [ $minute -le 60 ]; do
    printf "%02d:%02d\n" $hour $minute
    minute=$((minute+1))
    if [ $minute -eq 60 ]; then
	    hour=$((hour+1))
	    minute=0
    fi
done | head -n 70
