#!/usr/bin/env bash
#configures an Ubuntu server with the below requirem
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
#The checker is running on Docker, so make sure to read this
cp /etc/hosts new_hosts
sed -i s/^127.*/"127.0.0.2 localhost"/ new_hosts
echo "8.8.8.8 facebook.com" >> new_hosts
cp new_hosts /etc/hosts
